ARANOVAVendorBundle:
    resource: "@ARANOVAVendorBundle/Resources/config/routing.yml"
    prefix:   /

ARANOVADashboardBundle:
    resource: "@ARANOVADashboardBundle/Resources/config/routing.yml"
    prefix:   /

ARANOVAClientBundle:
    resource: "@ARANOVAClientBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
