ARANOVAContactBundle:
    resource: "@ARANOVAContactBundle/Controller/"
    type:     annotation
    prefix:   /contacts

ARANOVAClientBundle:
    resource: "@ARANOVAClientBundle/Controller/"
    type:     annotation
    prefix:   /clients

ARANOVAVendorBundle:
    resource: "@ARANOVAVendorBundle/Controller/"
    type:     annotation
    prefix:   /vendors

ARANOVADashboardBundle:
    resource: "@ARANOVADashboardBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
